### PR TITLE
Fix joining relative path in windows

### LINKED ISSUE #34: windows path handling
@zilbuz opened a bug in vitiral/artifact#247. They mentioned that it might be better addressed in `path_abs` and I agree.

Looking at https://docs.microsoft.com/fr-fr/windows/desktop/FileIO/naming-a-file#maxpath, it doesn't look like windows even allows `'/'` to be in the name of a file or a directory, so I don't see any harm in converting them. Honestly I thought we already did this.

### PR DESCRIPTION
**Pull request by zilbuz**
Fix #34

When joining path, the components of the path to join are pushed one by one
instead of using directly `PathBuf::join()`. Since `PathAbs` canonicalize the
path when calling `PahtAbs::new()`, the path is converted to extended length
path syntax on Windows. This syntax doesn't allow using '/'-separated path, but
Windows allows '/'-separated path otherwise. Joining the path component by
component permits `PathBuf` to do the right thing when joining a '/'-separated
relative path to a `PathAbs`.

### CODE REVIEW

File: src/arc.rs [hunk 1]
```diff
@@ -65,7 +65,15 @@ impl PathArc {
     ///
     /// [0]: https://doc.rust-lang.org/std/path/struct.PathBuf.html#method.join
     pub fn join<P: AsRef<Path>>(&self, path: P) -> PathArc {
-        PathArc::from(self.0.join(path))
+        // Clone the current path
```
Comment (vitiral) [inline src/arc.rs]: this comment can be removed.

File: src/arc.rs [hunk 2]
```diff
@@ -65,7 +65,15 @@ impl PathArc {
...
+        let mut joined_path = self.as_path().to_path_buf();
+        // Append the given path component by component so that path separator are correctly
+        // processed (see issue #34 for details).
+        for c in path.as_ref().components() {
+            joined_path.push(c);
+        }
+        // Return a new PathArc from the joined PathBuf
```
Comment (vitiral) [inline src/arc.rs]: this comment can be removed

File: src/arc.rs [hunk 3]
```diff
@@ -65,7 +65,15 @@ impl PathArc {
     ///
     /// [0]: https://doc.rust-lang.org/std/path/struct.PathBuf.html#method.join
     pub fn join<P: AsRef<Path>>(&self, path: P) -> PathArc {
-        PathArc::from(self.0.join(path))
+        // Clone the current path
+        let mut joined_path = self.as_path().to_path_buf();
+        // Append the given path component by component so that path separator are correctly
```
Comment (vitiral) [inline src/arc.rs]: Please change comment to something like:

```
// issue #34: windows preserves '\\' characters with `Path.push`.
```

Comment (zilbuz) [reply src/arc.rs]: What do you think of `// Issue #34: windows automatically convert '/' into '\\' with Path.push`? It seems clearer for me.

Comment (vitiral) [reply src/arc.rs]: Ya, something like that sounds better. Maybe:

```
// Issue #34: convert '/' into '\\' for windows
```
